[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any"]
set = true


[templates.colors_css]
input_path = './templates/colors.css'
output_path = '~/.config/colors.css'
post_hook = 'pkill -SIGUSR2 waybar;swaync-client -R -rs > /dev/null'


[templates.rofi]
input_path = './templates/rofi_colors.rasi'
output_path = '~/.config/rofi/colors.rasi'


[templates.hyprland]
input_path = './templates/hyprland_colors.conf'
output_path = '~/.config/hypr/colors.conf'


[templates.kitty]
input_path = './templates/kitty_colors.conf'
output_path = '~/.config/kitty/colors.conf'
